all: \
  Output/Debug/Obj/02drv_leds\
  Output/Debug/Exe\
  Output/Debug/Exe/02drv_leds.elf\

Output/Debug/Obj/02drv_leds:
	mkdir -p "Output/Debug/Obj/02drv_leds"
Output/Debug/Exe:
	mkdir -p "Output/Debug/Exe"

-include Output/Debug/Obj/02drv_leds/system_nrf52.d
Output/Debug/Obj/02drv_leds/system_nrf52.o:../common/nRF/Device/Source/system_nrf52.c
	/opt/SEGGER/segger_embedded_studio_8.24/bin/segger-cc -cc1 -disable-free -disable-llvm-verifier -fgnuc-version=4.2.1 -mrelocation-model static -mconstructor-aliases -x c -std=gnu99 -triple thumbv7em-none-eabi -target-cpu cortex-m4 -target-feature -strict-align -target-abi aapcs -mfloat-abi hard -fno-signed-char -fnative-half-type -fnative-half-arguments-and-returns -mllvm -arm-global-merge=false -nostdsysteminc -nobuiltininc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -dependency-file /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/system_nrf52.d -sys-header-deps -MT Output/Debug/Obj/02drv_leds/system_nrf52.o -dwarf-version=4 -debug-info-kind=standalone -debug-info-macro -debugger-tuning=gdb -mllvm -generate-arange-section -exception-model=dwarf -gpubnames -fno-dwarf-directory-asm -fmath-errno -ffunction-sections -fdata-sections -mtext=.init -mrodata=.init_rodata -fshort-enums -fno-common -main-file-name system_nrf52.c /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Source/system_nrf52.c -emit-obj -o Output/Debug/Obj/02drv_leds/system_nrf52.o

-include Output/Debug/Obj/02drv_leds/adc.d
Output/Debug/Obj/02drv_leds/adc.o:../common/bsp/adc.c
	/opt/SEGGER/segger_embedded_studio_8.24/bin/segger-cc -cc1 -disable-free -disable-llvm-verifier -fgnuc-version=4.2.1 -mrelocation-model static -mconstructor-aliases -x c -std=gnu99 -triple thumbv7em-none-eabi -target-cpu cortex-m4 -target-feature -strict-align -target-abi aapcs -mfloat-abi hard -fno-signed-char -fnative-half-type -fnative-half-arguments-and-returns -mllvm -arm-global-merge=false -nostdsysteminc -nobuiltininc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -dependency-file /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/adc.d -sys-header-deps -MT Output/Debug/Obj/02drv_leds/adc.o -dwarf-version=4 -debug-info-kind=standalone -debug-info-macro -debugger-tuning=gdb -mllvm -generate-arange-section -exception-model=dwarf -gpubnames -fno-dwarf-directory-asm -fmath-errno -ffunction-sections -fdata-sections -fshort-enums -fno-common -main-file-name adc.c /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/adc.c -emit-obj -o Output/Debug/Obj/02drv_leds/adc.o

-include Output/Debug/Obj/02drv_leds/board.d
Output/Debug/Obj/02drv_leds/board.o:../common/bsp/board.c
	/opt/SEGGER/segger_embedded_studio_8.24/bin/segger-cc -cc1 -disable-free -disable-llvm-verifier -fgnuc-version=4.2.1 -mrelocation-model static -mconstructor-aliases -x c -std=gnu99 -triple thumbv7em-none-eabi -target-cpu cortex-m4 -target-feature -strict-align -target-abi aapcs -mfloat-abi hard -fno-signed-char -fnative-half-type -fnative-half-arguments-and-returns -mllvm -arm-global-merge=false -nostdsysteminc -nobuiltininc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -dependency-file /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/board.d -sys-header-deps -MT Output/Debug/Obj/02drv_leds/board.o -dwarf-version=4 -debug-info-kind=standalone -debug-info-macro -debugger-tuning=gdb -mllvm -generate-arange-section -exception-model=dwarf -gpubnames -fno-dwarf-directory-asm -fmath-errno -ffunction-sections -fdata-sections -fshort-enums -fno-common -main-file-name board.c /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/board.c -emit-obj -o Output/Debug/Obj/02drv_leds/board.o

-include Output/Debug/Obj/02drv_leds/busywait.d
Output/Debug/Obj/02drv_leds/busywait.o:../common/bsp/busywait.c
	/opt/SEGGER/segger_embedded_studio_8.24/bin/segger-cc -cc1 -disable-free -disable-llvm-verifier -fgnuc-version=4.2.1 -mrelocation-model static -mconstructor-aliases -x c -std=gnu99 -triple thumbv7em-none-eabi -target-cpu cortex-m4 -target-feature -strict-align -target-abi aapcs -mfloat-abi hard -fno-signed-char -fnative-half-type -fnative-half-arguments-and-returns -mllvm -arm-global-merge=false -nostdsysteminc -nobuiltininc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -dependency-file /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/busywait.d -sys-header-deps -MT Output/Debug/Obj/02drv_leds/busywait.o -dwarf-version=4 -debug-info-kind=standalone -debug-info-macro -debugger-tuning=gdb -mllvm -generate-arange-section -exception-model=dwarf -gpubnames -fno-dwarf-directory-asm -fmath-errno -ffunction-sections -fdata-sections -fshort-enums -fno-common -main-file-name busywait.c /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/busywait.c -emit-obj -o Output/Debug/Obj/02drv_leds/busywait.o

-include Output/Debug/Obj/02drv_leds/gpio.d
Output/Debug/Obj/02drv_leds/gpio.o:../common/bsp/gpio.c
	/opt/SEGGER/segger_embedded_studio_8.24/bin/segger-cc -cc1 -disable-free -disable-llvm-verifier -fgnuc-version=4.2.1 -mrelocation-model static -mconstructor-aliases -x c -std=gnu99 -triple thumbv7em-none-eabi -target-cpu cortex-m4 -target-feature -strict-align -target-abi aapcs -mfloat-abi hard -fno-signed-char -fnative-half-type -fnative-half-arguments-and-returns -mllvm -arm-global-merge=false -nostdsysteminc -nobuiltininc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -dependency-file /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/gpio.d -sys-header-deps -MT Output/Debug/Obj/02drv_leds/gpio.o -dwarf-version=4 -debug-info-kind=standalone -debug-info-macro -debugger-tuning=gdb -mllvm -generate-arange-section -exception-model=dwarf -gpubnames -fno-dwarf-directory-asm -fmath-errno -ffunction-sections -fdata-sections -fshort-enums -fno-common -main-file-name gpio.c /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/gpio.c -emit-obj -o Output/Debug/Obj/02drv_leds/gpio.o

-include Output/Debug/Obj/02drv_leds/periodictimer.d
Output/Debug/Obj/02drv_leds/periodictimer.o:../common/bsp/periodictimer.c
	/opt/SEGGER/segger_embedded_studio_8.24/bin/segger-cc -cc1 -disable-free -disable-llvm-verifier -fgnuc-version=4.2.1 -mrelocation-model static -mconstructor-aliases -x c -std=gnu99 -triple thumbv7em-none-eabi -target-cpu cortex-m4 -target-feature -strict-align -target-abi aapcs -mfloat-abi hard -fno-signed-char -fnative-half-type -fnative-half-arguments-and-returns -mllvm -arm-global-merge=false -nostdsysteminc -nobuiltininc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -dependency-file /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/periodictimer.d -sys-header-deps -MT Output/Debug/Obj/02drv_leds/periodictimer.o -dwarf-version=4 -debug-info-kind=standalone -debug-info-macro -debugger-tuning=gdb -mllvm -generate-arange-section -exception-model=dwarf -gpubnames -fno-dwarf-directory-asm -fmath-errno -ffunction-sections -fdata-sections -fshort-enums -fno-common -main-file-name periodictimer.c /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/periodictimer.c -emit-obj -o Output/Debug/Obj/02drv_leds/periodictimer.o

-include Output/Debug/Obj/02drv_leds/leds.d
Output/Debug/Obj/02drv_leds/leds.o:../common/drv/leds/leds.c
	/opt/SEGGER/segger_embedded_studio_8.24/bin/segger-cc -cc1 -disable-free -disable-llvm-verifier -fgnuc-version=4.2.1 -mrelocation-model static -mconstructor-aliases -x c -std=gnu99 -triple thumbv7em-none-eabi -target-cpu cortex-m4 -target-feature -strict-align -target-abi aapcs -mfloat-abi hard -fno-signed-char -fnative-half-type -fnative-half-arguments-and-returns -mllvm -arm-global-merge=false -nostdsysteminc -nobuiltininc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -dependency-file /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/leds.d -sys-header-deps -MT Output/Debug/Obj/02drv_leds/leds.o -dwarf-version=4 -debug-info-kind=standalone -debug-info-macro -debugger-tuning=gdb -mllvm -generate-arange-section -exception-model=dwarf -gpubnames -fno-dwarf-directory-asm -fmath-errno -ffunction-sections -fdata-sections -fshort-enums -fno-common -main-file-name leds.c /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/leds.c -emit-obj -o Output/Debug/Obj/02drv_leds/leds.o

-include Output/Debug/Obj/02drv_leds/02drv_leds.d
Output/Debug/Obj/02drv_leds/02drv_leds.o:02drv_leds.c
	/opt/SEGGER/segger_embedded_studio_8.24/bin/segger-cc -cc1 -disable-free -disable-llvm-verifier -fgnuc-version=4.2.1 -mrelocation-model static -mconstructor-aliases -x c -std=gnu99 -triple thumbv7em-none-eabi -target-cpu cortex-m4 -target-feature -strict-align -target-abi aapcs -mfloat-abi hard -fno-signed-char -fnative-half-type -fnative-half-arguments-and-returns -mllvm -arm-global-merge=false -nostdsysteminc -nobuiltininc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -dependency-file /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/02drv_leds.d -sys-header-deps -MT Output/Debug/Obj/02drv_leds/02drv_leds.o -dwarf-version=4 -debug-info-kind=standalone -debug-info-macro -debugger-tuning=gdb -mllvm -generate-arange-section -exception-model=dwarf -gpubnames -fno-dwarf-directory-asm -fmath-errno -ffunction-sections -fdata-sections -fshort-enums -fno-common -main-file-name 02drv_leds.c /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/02drv_leds.c -emit-obj -o Output/Debug/Obj/02drv_leds/02drv_leds.o

-include Output/Debug/Obj/02drv_leds/nrf52833_Vectors.d
Output/Debug/Obj/02drv_leds/nrf52833_Vectors.o:../common/nRF/Source/nrf52833_Vectors.s
	/opt/SEGGER/segger_embedded_studio_8.24/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -lang-asm -fdiagnostics-color=never -fdiagnostics-show-caret -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -nostdinc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -MD /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/nrf52833_Vectors.d -MQ Output/Debug/Obj/02drv_leds/nrf52833_Vectors.o -quiet /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Source/nrf52833_Vectors.s -o /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/nrf52833_Vectors_PP.s
	/opt/SEGGER/segger_embedded_studio_8.24/gcc/arm-none-eabi/bin/as --traditional-format -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/nrf52833_Vectors_PP.s -o Output/Debug/Obj/02drv_leds/nrf52833_Vectors.o -g -gdwarf-4
	/opt/SEGGER/segger_embedded_studio_8.24/bin/rm -f /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/nrf52833_Vectors_PP.s

-include Output/Debug/Obj/02drv_leds/nRF_Startup.d
Output/Debug/Obj/02drv_leds/nRF_Startup.o:../common/nRF/Source/nRF_Startup.s
	/opt/SEGGER/segger_embedded_studio_8.24/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -lang-asm -fdiagnostics-color=never -fdiagnostics-show-caret -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -nostdinc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -MD /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/nRF_Startup.d -MQ Output/Debug/Obj/02drv_leds/nRF_Startup.o -quiet /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Source/nRF_Startup.s -o /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/nRF_Startup_PP.s
	/opt/SEGGER/segger_embedded_studio_8.24/gcc/arm-none-eabi/bin/as --traditional-format -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/nRF_Startup_PP.s -o Output/Debug/Obj/02drv_leds/nRF_Startup.o -g -gdwarf-4
	/opt/SEGGER/segger_embedded_studio_8.24/bin/rm -f /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/nRF_Startup_PP.s

-include Output/Debug/Obj/02drv_leds/SEGGER_THUMB_Startup.d
Output/Debug/Obj/02drv_leds/SEGGER_THUMB_Startup.o:../common/SEGGER_THUMB_Startup.s
	/opt/SEGGER/segger_embedded_studio_8.24/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -lang-asm -fdiagnostics-color=never -fdiagnostics-show-caret -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -munaligned-access -nostdinc -isystem/opt/SEGGER/segger_embedded_studio_8.24/include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=1024 -D__SEGGER_LINKER -D__SES_VERSION=82400 -DDEBUG -DARM_MATH_CM4 -DNRF52833_XXAA -D__NRF_FAMILY -MD /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/SEGGER_THUMB_Startup.d -MQ Output/Debug/Obj/02drv_leds/SEGGER_THUMB_Startup.o -quiet /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/SEGGER_THUMB_Startup.s -o /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/SEGGER_THUMB_Startup_PP.s
	/opt/SEGGER/segger_embedded_studio_8.24/gcc/arm-none-eabi/bin/as --traditional-format -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/CMSIS_5/CMSIS/Core/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/nRF/Device/Include -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/bsp/ -I/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/common/drv/leds/ -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/SEGGER_THUMB_Startup_PP.s -o Output/Debug/Obj/02drv_leds/SEGGER_THUMB_Startup.o -g -gdwarf-4
	/opt/SEGGER/segger_embedded_studio_8.24/bin/rm -f /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Obj/02drv_leds/SEGGER_THUMB_Startup_PP.s

Output/Debug/Exe/02drv_leds.elf:\
  Output/Debug/Obj/02drv_leds/system_nrf52.o\
  Output/Debug/Obj/02drv_leds/adc.o\
  Output/Debug/Obj/02drv_leds/board.o\
  Output/Debug/Obj/02drv_leds/busywait.o\
  Output/Debug/Obj/02drv_leds/gpio.o\
  Output/Debug/Obj/02drv_leds/periodictimer.o\
  Output/Debug/Obj/02drv_leds/leds.o\
  Output/Debug/Obj/02drv_leds/02drv_leds.o\
  Output/Debug/Obj/02drv_leds/nrf52833_Vectors.o\
  Output/Debug/Obj/02drv_leds/nRF_Startup.o\
  Output/Debug/Obj/02drv_leds/SEGGER_THUMB_Startup.o\
  /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/../common/nRF_Flash_Variant1.icf
	/opt/SEGGER/segger_embedded_studio_8.24/bin/segger-ld --add-region:FLASH1=0x00080000@0x00000000 --add-region:CODE_RAM1=0x00020000@0x00800000 --add-region:RAM1=0x00020000@0x20000000 --full-section-headers --merge-sections --merge-strings --map-text --map-file=Output/Debug/Exe/02drv_leds.map --map-standard -eReset_Handler -EL -mcpu=7E-M --silent --list-all-undefineds -T/home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/../common/nRF_Flash_Variant1.icf --defsym=__STACKSIZE__=2048 --defsym=__STACKSIZE_PROCESS__=0 --defsym=__HEAPSIZE__=1024 --defsym=__SEGGER_RTL_vfprintf=__SEGGER_RTL_vfprintf_int_nwp --defsym=__SEGGER_RTL_vfscanf=__SEGGER_RTL_vfscanf_int -u_vectors -o /home/pierre/Documents/ENSTA/IC212/MagicLight/aiot_play_fw/02drv_leds/Output/Debug/Exe/02drv_leds.elf Output/Debug/Obj/02drv_leds/system_nrf52.o Output/Debug/Obj/02drv_leds/adc.o Output/Debug/Obj/02drv_leds/board.o Output/Debug/Obj/02drv_leds/busywait.o Output/Debug/Obj/02drv_leds/gpio.o Output/Debug/Obj/02drv_leds/periodictimer.o Output/Debug/Obj/02drv_leds/leds.o Output/Debug/Obj/02drv_leds/02drv_leds.o Output/Debug/Obj/02drv_leds/nrf52833_Vectors.o Output/Debug/Obj/02drv_leds/nRF_Startup.o Output/Debug/Obj/02drv_leds/SEGGER_THUMB_Startup.o /opt/SEGGER/segger_embedded_studio_8.24/lib/libc_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a /opt/SEGGER/segger_embedded_studio_8.24/lib/SEGGER_crtinit_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a /opt/SEGGER/segger_embedded_studio_8.24/lib/prinops_rtt_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a /opt/SEGGER/segger_embedded_studio_8.24/lib/heapops_basic_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a /opt/SEGGER/segger_embedded_studio_8.24/lib/heapops_disable_interrupts_locking_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a /opt/SEGGER/segger_embedded_studio_8.24/lib/strops_unaligned_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a /opt/SEGGER/segger_embedded_studio_8.24/lib/mbops_timeops_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a